// Background score — a single <Audio> that carries a looped, fade-in/fade-out mood bed
// under the whole clip. Remotion muxes the audio into the MP4 by default, so no extra
// step is needed at render time. Frame-driven volume (no CSS), so it's deterministic.
//
// The mood beds live at public/music/<mood>.mp3 and are generated by make-scores.mjs
// (run from render.sh before rendering). If a bed is missing, render the clip mute by
// passing music=false in props (render.sh patches props.json when generation fails).

import React from "react";
import { Audio, interpolate, staticFile, useVideoConfig } from "remotion";
import type { Mood } from "./types";
import { MOOD_FILE } from "./moods";
import { FPS } from "./tokens";

export const BackgroundScore: React.FC<{ mood: Mood; volume?: number }> = ({
  mood,
  // Music-only clip (no voiceover), so the bed should be clearly audible, not a faint
  // undertone. The beds are mid-forward + carry a melodic arp (engine make-scores.mjs), so
  // ~0.92 lands the muxed track around -14 LUFS — clearly audible on phone/laptop speakers.
  volume = 0.92,
}) => {
  const { durationInFrames } = useVideoConfig();
  const fadeIn = Math.min(Math.round(0.8 * FPS), Math.floor(durationInFrames / 4));
  const fadeOut = Math.min(Math.round(1.3 * FPS), Math.floor(durationInFrames / 3));
  const src = staticFile(MOOD_FILE[mood] ?? MOOD_FILE.calm);
  return (
    <Audio
      src={src}
      loop
      volume={(f) =>
        interpolate(
          f,
          [0, fadeIn, Math.max(fadeIn + 1, durationInFrames - fadeOut), durationInFrames],
          [0, volume, volume, 0],
          { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
        )
      }
    />
  );
};
